### ISSUE TITLE
Часть текста не переводится на русский в Safari iOS

### ISSUE THREAD

**Issue by andres-website** [MeFoDy/mefody.dev#1]
Привет. Когда включён автоперевод в Safari iOS. Часть текста переводится, а часть нет. Подробности в скриншоте.
![0706D09C-725A-4D8B-A421-3C5917193DC3](https://user-images.githubusercontent.com/22051337/114724635-f7d32600-9d65-11eb-9618-0deb421bd476.png)

Спасибо.

**Comment by MeFoDy** [comment]
Эта функциональность ещё в Бете для Safari, поэтому в ней могут быть баги (и они есть). Документации о том, как им помочь переводить, я не нашёл. Скорее всего, ломается там, где парсер находит `code` и `pre`.

Давайте дождёмся официальной документации по переводам, тогда я попробую оптимизировать сайт под это дело. Пока ишью закрою.
